
import { useState } from "react";
import { MainLayout } from "@/components/layout/MainLayout";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Wand2, Copy, Trash, Loader2 } from "lucide-react";
import { useToast } from "@/hooks/use-toast";

const TextGenerationPage = () => {
  const [prompt, setPrompt] = useState("");
  const [generatedText, setGeneratedText] = useState("");
  const [isGenerating, setIsGenerating] = useState(false);
  const [selectedModel, setSelectedModel] = useState("gpt-4");
  const [selectedTask, setSelectedTask] = useState("creative");
  const { toast } = useToast();

  const tasks = {
    creative: {
      title: "Creative Writing",
      placeholder: "Write a prompt for creative text generation...",
      examples: [
        "Write a short story about a robot discovering emotions",
        "Create a poem about autumn leaves falling",
        "Write a movie scene where two strangers meet on a train"
      ]
    },
    summarize: {
      title: "Summarization",
      placeholder: "Paste text to summarize...",
      examples: [
        "Summarize this scientific article",
        "Give me the key points from this news report",
        "Extract the main ideas from this speech"
      ]
    },
    translate: {
      title: "Translation",
      placeholder: "Enter text to translate...",
      examples: [
        "Translate this paragraph to Spanish",
        "Convert this text from English to French",
        "Translate these instructions to Japanese"
      ]
    }
  };

  const generateText = () => {
    if (!prompt.trim()) return;
    
    setIsGenerating(true);
    
    // Simulate text generation
    setTimeout(() => {
      const taskType = selectedTask === "creative" ? "creative writing" : 
                      selectedTask === "summarize" ? "summary" : "translation";
                      
      setGeneratedText(`This is a simulated ${taskType} generated by the ${selectedModel} model. In a real implementation, this would use an actual LLM API to process your prompt: "${prompt}".`);
      setIsGenerating(false);
    }, 1500);
  };

  const copyToClipboard = () => {
    navigator.clipboard.writeText(generatedText);
    toast({
      title: "Copied to clipboard",
      description: "The generated text has been copied to your clipboard."
    });
  };

  const clearAll = () => {
    setPrompt("");
    setGeneratedText("");
  };

  return (
    <MainLayout>
      <div className="flex flex-col">
        <div className="pb-4 flex items-center justify-between">
          <h1 className="text-3xl font-bold tracking-tight">Text Generation</h1>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          <div className="space-y-4">
            <Tabs defaultValue="creative" value={selectedTask} onValueChange={setSelectedTask}>
              <TabsList className="w-full">
                <TabsTrigger value="creative" className="flex-1">Creative</TabsTrigger>
                <TabsTrigger value="summarize" className="flex-1">Summarize</TabsTrigger>
                <TabsTrigger value="translate" className="flex-1">Translate</TabsTrigger>
              </TabsList>
            </Tabs>

            <Card className="flex-1">
              <CardHeader className="pb-2">
                <div className="flex items-center justify-between">
                  <CardTitle>{tasks[selectedTask as keyof typeof tasks].title}</CardTitle>
                  <Select value={selectedModel} onValueChange={setSelectedModel}>
                    <SelectTrigger className="w-40">
                      <SelectValue placeholder="Select model" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="gpt-4">GPT-4</SelectItem>
                      <SelectItem value="gemini">Gemini</SelectItem>
                      <SelectItem value="claude">Claude</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
              </CardHeader>
              <CardContent>
                <Textarea
                  placeholder={tasks[selectedTask as keyof typeof tasks].placeholder}
                  value={prompt}
                  onChange={(e) => setPrompt(e.target.value)}
                  className="min-h-[200px] resize-none"
                />
                <div className="mt-2 text-sm text-muted-foreground">
                  <p>Example prompts:</p>
                  <ul className="list-disc list-inside mt-1 space-y-1">
                    {tasks[selectedTask as keyof typeof tasks].examples.map((example, i) => (
                      <li key={i} className="cursor-pointer hover:text-primary" onClick={() => setPrompt(example)}>
                        {example}
                      </li>
                    ))}
                  </ul>
                </div>
                <div className="flex justify-between mt-4">
                  <Button variant="outline" onClick={clearAll}>
                    <Trash className="h-4 w-4 mr-2" />
                    Clear
                  </Button>
                  <Button onClick={generateText} disabled={!prompt.trim() || isGenerating}>
                    {isGenerating ? (
                      <>
                        <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                        Generating...
                      </>
                    ) : (
                      <>
                        <Wand2 className="h-4 w-4 mr-2" />
                        Generate
                      </>
                    )}
                  </Button>
                </div>
              </CardContent>
            </Card>
          </div>

          <Card className="flex-1">
            <CardHeader className="pb-2">
              <div className="flex justify-between items-center">
                <CardTitle>Generated Output</CardTitle>
                {generatedText && (
                  <Button variant="outline" size="sm" onClick={copyToClipboard}>
                    <Copy className="h-4 w-4 mr-2" />
                    Copy
                  </Button>
                )}
              </div>
            </CardHeader>
            <CardContent>
              <div className="min-h-[300px] p-4 bg-secondary/50 rounded-md">
                {isGenerating ? (
                  <div className="h-full flex items-center justify-center">
                    <Loader2 className="h-8 w-8 animate-spin text-muted-foreground" />
                  </div>
                ) : generatedText ? (
                  <div className="whitespace-pre-wrap">{generatedText}</div>
                ) : (
                  <div className="h-full flex items-center justify-center text-muted-foreground">
                    Your generated text will appear here
                  </div>
                )}
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </MainLayout>
  );
};

export default TextGenerationPage;
