
import { useState, useEffect } from "react";
import { MainLayout } from "@/components/layout/MainLayout";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Wand2, Copy, Trash, Loader2, BookmarkPlus, History } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import ConversationHistoryDrawer from "@/components/history/ConversationHistoryDrawer";
import { ConversationHistory } from "@/hooks/use-conversation-history";
import { useAuth } from "@/contexts/AuthContext";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

const TextGenerationPage = () => {
  const [prompt, setPrompt] = useState("");
  const [generatedText, setGeneratedText] = useState("");
  const [isGenerating, setIsGenerating] = useState(false);
  const [selectedModel, setSelectedModel] = useState("gpt-4");
  const [selectedTask, setSelectedTask] = useState("creative");
  const [saveTitle, setSaveTitle] = useState("");
  const [showSaveDialog, setShowSaveDialog] = useState(false);
  const { toast } = useToast();
  const { user } = useAuth();

  // Clear save dialog when changing tasks
  useEffect(() => {
    setSaveTitle("");
  }, [selectedTask]);

  const tasks = {
    creative: {
      title: "Creative Writing",
      placeholder: "Write a prompt for creative text generation...",
      examples: [
        "Write a short story about a robot discovering emotions",
        "Create a poem about autumn leaves falling",
        "Write a movie scene where two strangers meet on a train"
      ]
    },
    summarize: {
      title: "Summarization",
      placeholder: "Paste text to summarize...",
      examples: [
        "Summarize this scientific article",
        "Give me the key points from this news report",
        "Extract the main ideas from this speech"
      ]
    },
    translate: {
      title: "Translation",
      placeholder: "Enter text to translate...",
      examples: [
        "Translate this paragraph to Spanish",
        "Convert this text from English to French",
        "Translate these instructions to Japanese"
      ]
    }
  };

  const generateText = () => {
    if (!prompt.trim()) return;
    
    setIsGenerating(true);
    
    // Generate a default save title based on the prompt
    const defaultTitle = prompt.slice(0, 30) + (prompt.length > 30 ? "..." : "");
    setSaveTitle(defaultTitle);
    
    // Simulate text generation
    setTimeout(() => {
      const taskType = selectedTask === "creative" ? "creative writing" : 
                      selectedTask === "summarize" ? "summary" : "translation";
                      
      setGeneratedText(`This is a simulated ${taskType} generated by the ${selectedModel} model. In a real implementation, this would use an actual LLM API to process your prompt: "${prompt}".`);
      setIsGenerating(false);
    }, 1500);
  };

  const copyToClipboard = () => {
    navigator.clipboard.writeText(generatedText);
    toast({
      title: "Copied to clipboard",
      description: "The generated text has been copied to your clipboard."
    });
  };

  const clearAll = () => {
    setPrompt("");
    setGeneratedText("");
    setSaveTitle("");
  };

  const saveConversation = async () => {
    const title = saveTitle || "Untitled conversation";
    
    try {
      // Implement your save functionality here using the useConversationHistory hook
      // Example:
      // await saveHistory(title, {
      //   prompt,
      //   response: generatedText,
      //   model: selectedModel,
      //   task: selectedTask
      // });
      
      toast({
        title: "Conversation saved",
        description: "Your conversation has been saved to history."
      });
      
      setShowSaveDialog(false);
    } catch (error: any) {
      toast({
        title: "Error saving conversation",
        description: error.message,
        variant: "destructive"
      });
    }
  };

  const handleHistorySelect = (history: ConversationHistory) => {
    if (history.content) {
      const content = history.content as any;
      setPrompt(content.prompt || "");
      setGeneratedText(content.response || "");
      setSelectedModel(content.model || "gpt-4");
      setSelectedTask(content.task || "creative");
      
      toast({
        title: "Conversation restored",
        description: "Previous conversation has been loaded."
      });
    }
  };

  return (
    <MainLayout>
      <div className="flex flex-col">
        <div className="pb-4 flex items-center justify-between">
          <h1 className="text-3xl font-bold tracking-tight">Text Generation</h1>
          <div className="flex gap-2">
            <ConversationHistoryDrawer
              type="chat"
              onSelectHistory={handleHistorySelect}
              trigger={
                <Button variant="outline" size="sm">
                  <History className="h-4 w-4 mr-2" />
                  History
                </Button>
              }
            />
          </div>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          <div className="space-y-4">
            <Tabs defaultValue="creative" value={selectedTask} onValueChange={setSelectedTask}>
              <TabsList className="w-full">
                <TabsTrigger value="creative" className="flex-1">Creative</TabsTrigger>
                <TabsTrigger value="summarize" className="flex-1">Summarize</TabsTrigger>
                <TabsTrigger value="translate" className="flex-1">Translate</TabsTrigger>
              </TabsList>
            </Tabs>

            <Card className="flex-1">
              <CardHeader className="pb-2">
                <div className="flex items-center justify-between">
                  <CardTitle>{tasks[selectedTask as keyof typeof tasks].title}</CardTitle>
                  <Select value={selectedModel} onValueChange={setSelectedModel}>
                    <SelectTrigger className="w-40">
                      <SelectValue placeholder="Select model" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="gpt-4">GPT-4</SelectItem>
                      <SelectItem value="gemini">Gemini</SelectItem>
                      <SelectItem value="claude">Claude</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
              </CardHeader>
              <CardContent>
                <Textarea
                  placeholder={tasks[selectedTask as keyof typeof tasks].placeholder}
                  value={prompt}
                  onChange={(e) => setPrompt(e.target.value)}
                  className="min-h-[200px] resize-none"
                />
                <div className="mt-2 text-sm text-muted-foreground">
                  <p>Example prompts:</p>
                  <ul className="list-disc list-inside mt-1 space-y-1">
                    {tasks[selectedTask as keyof typeof tasks].examples.map((example, i) => (
                      <li key={i} className="cursor-pointer hover:text-primary" onClick={() => setPrompt(example)}>
                        {example}
                      </li>
                    ))}
                  </ul>
                </div>
                <div className="flex justify-between mt-4">
                  <Button variant="outline" onClick={clearAll}>
                    <Trash className="h-4 w-4 mr-2" />
                    Clear
                  </Button>
                  <Button onClick={generateText} disabled={!prompt.trim() || isGenerating}>
                    {isGenerating ? (
                      <>
                        <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                        Generating...
                      </>
                    ) : (
                      <>
                        <Wand2 className="h-4 w-4 mr-2" />
                        Generate
                      </>
                    )}
                  </Button>
                </div>
              </CardContent>
            </Card>
          </div>

          <Card className="flex-1">
            <CardHeader className="pb-2">
              <div className="flex justify-between items-center">
                <CardTitle>Generated Output</CardTitle>
                {generatedText && (
                  <div className="flex gap-2">
                    <Button variant="outline" size="sm" onClick={() => setShowSaveDialog(true)}>
                      <BookmarkPlus className="h-4 w-4 mr-2" />
                      Save
                    </Button>
                    <Button variant="outline" size="sm" onClick={copyToClipboard}>
                      <Copy className="h-4 w-4 mr-2" />
                      Copy
                    </Button>
                  </div>
                )}
              </div>
            </CardHeader>
            <CardContent>
              {showSaveDialog && generatedText ? (
                <div className="space-y-4 p-4 bg-secondary/50 rounded-md">
                  <div className="space-y-2">
                    <Label htmlFor="save-title">Save as</Label>
                    <Input
                      id="save-title"
                      value={saveTitle}
                      onChange={(e) => setSaveTitle(e.target.value)}
                      placeholder="Enter a title for this conversation"
                    />
                  </div>
                  <div className="flex justify-end gap-2">
                    <Button variant="outline" onClick={() => setShowSaveDialog(false)}>
                      Cancel
                    </Button>
                    <Button onClick={saveConversation}>
                      Save
                    </Button>
                  </div>
                </div>
              ) : (
                <div className="min-h-[300px] p-4 bg-secondary/50 rounded-md">
                  {isGenerating ? (
                    <div className="h-full flex items-center justify-center">
                      <Loader2 className="h-8 w-8 animate-spin text-muted-foreground" />
                    </div>
                  ) : generatedText ? (
                    <div className="whitespace-pre-wrap">{generatedText}</div>
                  ) : (
                    <div className="h-full flex items-center justify-center text-muted-foreground">
                      Your generated text will appear here
                    </div>
                  )}
                </div>
              )}
            </CardContent>
          </Card>
        </div>
      </div>
    </MainLayout>
  );
};

export default TextGenerationPage;
