
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://svsbaatlenynjgrqysro.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN2c2JhYXRsZW55bmpncnF5c3JvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5Mjg1MzgsImV4cCI6MjA1ODUwNDUzOH0.BOO2zUrWApIcfPdGSSxLnba6ohyZvr84PSQIS964Sg4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true, 
    autoRefreshToken: true,
  }
});

// Initialize storage bucket for avatars if not exists
(async () => {
  try {
    const { data: buckets } = await supabase.storage.listBuckets();
    if (!buckets?.find(bucket => bucket.name === 'avatars')) {
      await supabase.storage.createBucket('avatars', {
        public: true,
      });
      
      // Set up policy to allow users to upload their avatars
      await supabase.storage.from('avatars').createSignedUploadUrl('init');
    }
  } catch (error) {
    console.error('Error initializing storage:', error);
  }
})();
