
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY as string;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error('Supabase environment variables are not set');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true, 
    autoRefreshToken: true,
  }
});

// Helper function to convert Message object to JSON-safe format
export function messageToJson(message: any): any {
  if (typeof message === 'object' && message !== null) {
    if (message instanceof Date) {
      return message.toISOString();
    }
    
    // If it's an array, convert each item
    if (Array.isArray(message)) {
      return message.map(messageToJson);
    }
    
    // Process object properties
    const result: Record<string, any> = {};
    for (const key in message) {
      if (Object.prototype.hasOwnProperty.call(message, key)) {
        result[key] = messageToJson(message[key]);
      }
    }
    return result;
  }
  
  // Return primitive values as is
  return message;
}

// Initialize storage bucket for avatars if not exists
(async () => {
  try {
    const { data: buckets } = await supabase.storage.listBuckets();
    if (!buckets?.find(bucket => bucket.name === 'avatars')) {
      await supabase.storage.createBucket('avatars', {
        public: true,
      });
      
      // Set up policy to allow users to upload their avatars
      await supabase.storage.from('avatars').createSignedUploadUrl('init');
    }
  } catch (error) {
    console.error('Error initializing storage:', error);
  }
})();
